# Generated by Django 4.2.16 on 2024-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Azon', models.CharField(max_length=10)),
                ('Nev', models.CharField(max_length=100)),
                ('Kategoria', models.CharField(max_length=50)),
                ('Kiszereles', models.CharField(max_length=10)),
                ('Ar', models.IntegerField()),
            ],
        ),
    ]
